services:
  mysql:
    image: mysql:8.0
    container_name: mysql_books_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_books
      MYSQL_USER: user_books
      MYSQL_PASSWORD: books123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB/spring-security-schema-bcrypt.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books_network
    restart: no
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  books_network:
    driver: bridge
